apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/gradle/pullrequest.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - name: list-env-vars
          image: busybox
          command:
            - "sh"
            - "-c"
          args:
            - "env"
          resources: {}
        - image: gradle:8.10.2-jdk21
          name: build-gradle-build
          resources: {}
          continueAfterSkip: true
          script: |
            #!/bin/sh
            gradle clean build || echo "Gradle build failed but continuing the pipeline" && exit 0
        - image: alpine:latest
          name: upload-artifacts
          resources: { }
          script: |
            #!/bin/sh
            apk add --no-cache curl ca-certificates

            echo "Downloading mc:"
            curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
            echo "Downloaded mc:"
            ls -la | grep mc

            chmod +x mc
            mv mc /usr/local/bin/

            echo "mc version:"
            mc --version
            
            mc alias set myminio http://minio.jx.svc.cluster.local:9000 rootUser rootpass123
            echo "Checking mc alias:"
            mc alias list

            echo "Creating bucket jx-artifacts:"
            mc mb myminio/jx-artifacts

            echo "Copying /build:"
            mc cp --recursive /workspace/source/backend/build/ myminio/jx-artifacts/workspace/source/backend/build/
        - name: check-registry
          resources: {}
        - image: gcr.io/kaniko-project/executor:v1.23.2-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds/.docker/config.json /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - name: promote-jx-preview
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
