apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/gradle/pullrequest.yaml@versionStream
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: git-clone-pr
        - name: jx-variables
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - name: list-env-vars
          image: busybox
          command:
            - "sh"
            - "-c"
          args:
            - "env"
        - image: gradle:8.10.2-jdk21
          name: build-gradle-build
          script: |
            #!/bin/sh
            echo "Running Gradle build"
            gradle clean build || exit 1
            echo "Copying test artifacts"
            mkdir -p /workspace/source/artifacts/reports
            cp -r ./backend/build/reports/* /workspace/source/artifacts/reports/
            echo "Test artifacts copied to /workspace/source/artifacts/reports/"
        - name: check-registry
        - image: gcr.io/kaniko-project/executor:v1.23.2-debug
          name: build-container-build
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds/.docker/config.json /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - name: promote-jx-preview
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
