apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/gradle/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        - image: gradle:8.10.2-jdk21
          name: build-gradle-build
          resources: {}
          script: |
            #!/bin/sh
            gradle clean build
        - name: check-registry
          resources: {}
        - image: gcr.io/kaniko-project/executor:v1.23.2-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds/.docker/config.json /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - name: promote-changelog
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.11.3
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            echo "Logging into OCI registry with insecure TLS skip..."
            echo admin | helm registry login $DOCKER_REGISTRY --username admin --password-stdin --insecure
            echo "Releasing Helm chart..."
            export HELM_OPTS="--insecure-skip-tls-verify"
            jx gitops helm release --oci --no-oci-login --repo-url $DOCKER_REGISTRY --version $VERSION --charts-dir ./charts
        - name: promote-jx-promote
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
